# Generated by Django 4.2 on 2023-05-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[{'ČŠ', 'Čišćenje'}, {'LO', 'Losioni'}, {'MA', 'Maske'}, {'I_Serumi', 'IS'}, {'CS', 'C_Serumi'}, {'Kreme', 'KR'}, {'ZS', 'Z_Serumi'}, {'K_Pilinzi', 'KP'}, {'GreenPeel', 'GP'}], max_length=9)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
