# Generated by Django 4.2 on 2023-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ČŠ', 'Čišćenje'), ('LO', 'Losioni'), ('MA', 'Maske'), ('IS', 'Izvorni Serumi'), ('CS', 'Ciljani Serumi'), ('KR', 'Kreme'), ('ZS', 'Završni Serumi'), ('KP', 'Kemijski Pilinzi'), ('GP', 'GreenPeel')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
