# Generated by Django 4.2 on 2023-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_composition_remove_product_prodapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CI', 'Čišćenje'), ('LO', 'Losioni'), ('MA', 'Maske'), ('IS', 'Izvorni Serumi'), ('CS', 'Ciljani Serumi'), ('KR', 'Kreme'), ('ZS', 'Završni Serumi'), ('KP', 'Kemijski Pilinzi'), ('GP', 'GreenPeel')], max_length=2),
        ),
    ]
